### PR TITLE
Class 5th to 8th programs

### PR DESCRIPTION
**Pull request by prabhant**
these are some programs that we can work on for school kids
* these programs are directly linked with the school's in maths

### CODE REVIEW

**Comment by vnbang2003** [comment]
@prabhant : This look good. Is it possible for you add more like this 
https://github.com/kracekumar/learnpythoninminutes
https://gist.github.com/pshirali/b11ab5bff8d79c472a6019221d30e7a3

**Comment by prabhant** [comment]
Yes I'll be adding more for 9-10th class too.
But it will take time, since in their syllabus programming can be
applicable at a lot of places.
Plus I'm planning to use the numpy scipy and pandas in their curriculum.

**Comment by prabhant** [comment]
I have checked the link
they are mainly python101 tutorials, the problem with them is that you
cannot grab the attention of the smaller kids by teaching them about the
basics of programming language(it's really boring for them), but then when
they see the uses of the language then we can teach them about the
functions, strings and data types. Till then I prefer that we should them
the practical programming which can be used to solve their everyday
troubles(maths).

**Comment by vnbang2003** [comment]
I just gave refence to you that if we can add example program also in the content so it easy for other to use material when they condcut workshop at schools.

**Comment by prabhant** [comment]
Okie
So should I add the programs also from the next PR with a jupyter notebook?

**Comment by vnbang2003** [comment]
@prabhant Sorry had lost track of this . Yes if you could add it would be awesome.

**Pull request merged**
